### ISSUE TITLE
error: Could not find 'zathura_plugin_6_7'

### ISSUE THREAD

**Issue by thomascrha** [thrombe/zathura-images#1]
Howdy, 

I'm having some issues with getting this plugin working. I've installed the deps from the page linked including imagemagick - was able to compile and then place the shared object file into zathura and I get this error

```
error: Could not find 'zathura_plugin_6_7' in plugin /usr/lib/zathura/libzathura-images.so - is not a plugin or needs to be rebuilt.
```

System: Linux 6.11.8-arch1-2 #1 SMP PREEMPT_DYNAMIC Fri, 15 Nov 2024 15:35:07 +0000 x86_64 GNU/Linux
zathura 0.5.8
girara 0.4.4 (runtime: 0.4.4)
(plugin) pdf-mupdf (0.4.4) (/usr/lib/zathura/libpdf-mupdf.so)

**Comment by thrombe** [comment]
fixed in 63ea754. didn't realize zathura's plugin api version bumped again. let me know if you have any more issues with this :)
